version: 3
networks: 
  auth:
    external:
      name: auth

############
# 基盤
############
services:

  redis:
      image: "redis:latest"
      networks: 
        - auth

  mysql:
    build: 
      context: ./docker/mysql
    container_name: "auth_db"
    volumes:
      - ./logs/mysql:/var/log/mysql
    environment :
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - "TZ=Asia/Tokyo"
    ports:
      - ${DB_PORT}:3306
    networks: 
      - auth